version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/swift-api-gateway"
    schedule:
      interval: monthly
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly