name: Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: ["17", "21"]
        os: ["ubuntu-latest"]
    env:
      CONSUMER_KEY_BNKABEBB: ${{ vars.CONSUMER_KEY }}
      CONSUMER_SECRET_BNKABEBB: ${{ secrets.CONSUMER_SECRET }}
      CONSUMER_KEY_BNKBBEBB: ${{ vars.CONSUMER_KEY }}
      CONSUMER_SECRET_BNKBBEBB: ${{ secrets.CONSUMER_SECRET }}
    name: Build and Test ${{ matrix.Java }} (${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"
      - name: Test
        working-directory: swift-api-gateway
        run: ./mvnw -B verify --file pom.xml